### ISSUE TITLE
Questions about the code #

### ISSUE THREAD

**Issue by caojunlin** [LDOUBLEV/style_transfer-perceptual_loss#3]
Traceback (most recent call last):                                                                   File "train.py", line 193, in <module>                                                               Model.build_model()                                                                              File "train.py", line 65, in build_model                                                             imgs = load_data.get_loader(data_path, self.batch_size, self.img_size)                           File "D:\Python\Anaconda\Tensorflow\learning\tensorflow1\style_transfer\style_transfer-perceptual_loss-master\style_transfer-perceptual_loss-master\vlib\load_data.py", line 29, in get_loader          with Image.open(path[0]) as img:                                                               IndexError: list index out of range    

![image](https://user-images.githubusercontent.com/26141822/43043001-1d3aeb60-8dbc-11e8-8623-5cd8de66974e.png)

为什么会发生这样的情况，我是按照你给的代码运行的，希望你能答复一下

**Comment by LDOUBLEV** [comment]
@caojunlin 你应该是没有读到数据，path里面是空

**Comment by XeniaLLL** [comment]
请问博主我在测试的时候，添加了参数-is_training=False,但是运行的时候打印为True（只有不给这个参数才会是False）,这是为什么呢 @LDOUBLEV

**Comment by wangshuai66666** [comment]
我也发现这个问题，请问你测试成功了吗？ @XeniaLLL
